name       : lm_sensors
version    : 3.5.0
release    : 6
source     :
    - https://github.com/lm-sensors/lm-sensors/archive/V3-5-0.tar.gz : f671c1d63a4cd8581b3a4a775fd7864a740b15ad046fe92038bcff5c5134d7e0
homepage   : https://hwmon.wiki.kernel.org/lm_sensors
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
summary    : User space hardware monitoring
component  : system.utils
description: |
    User-space support for the hardware monitoring drivers in the Linux kernel
build      : |
    %make EXLDFLAGS="$LDFLAGS"
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir% MANDIR=/usr/share/man \
        BUILD_STATIC_LIB=0 EXLDFLAGS="$LDFLAGS"

    # install systemd units manually as this is not done via the Makefile's install target
    mkdir -p $installdir/usr/lib/systemd/system/
    install -Dm00644 prog/init/{fancontrol,lm_sensors}.service $installdir/usr/lib/systemd/system/
