name       : lm_sensors
version    : 3.6.0
release    : 7
source     :
    - https://github.com/lm-sensors/lm-sensors/archive/V3-6-0.tar.gz : 0591f9fa0339f0d15e75326d0365871c2d4e2ed8aa1ff759b3a55d3734b7d197
homepage   : https://hwmon.wiki.kernel.org/lm_sensors
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
summary    : User space hardware monitoring
component  : system.utils
description: |
    User-space support for the hardware monitoring drivers in the Linux kernel
build      : |
    %make EXLDFLAGS="$LDFLAGS"
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir% MANDIR=/usr/share/man \
        BUILD_STATIC_LIB=0 EXLDFLAGS="$LDFLAGS"

    # install systemd units manually as this is not done via the Makefile's install target
    mkdir -p $installdir/usr/lib/systemd/system/
    install -Dm00644 prog/init/{fancontrol,lm_sensors}.service $installdir/usr/lib/systemd/system/
