name       : lm_sensors
version    : 3.4.0
release    : 5
source     :
    - https://github.com/groeck/lm-sensors/archive/V3-4-0.tar.gz : e334c1c2b06f7290e3e66bdae330a5d36054701ffd47a5dde7a06f9a7402cb4e
homepage   : http://lm-sensors.org/
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : User space hardware monitoring
component  : system.utils
description: |
    User-space support for the hardware monitoring drivers in the Linux kernel
build      : |
    %make
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir% BUILD_STATIC_LIB=0 MANDIR=/usr/share/man
    # install systemd units manually as this is not done via the Makefile's install target
    mkdir -p $installdir/usr/lib/systemd/system/
    install -Dm00644 $workdir/prog/init/*.service $installdir/usr/lib/systemd/system/
